backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
display_url: https://www.dashword.net
media_folder: "_src/assets/img"
public_folder: "/assets/img"
logo_url: https://www.dashword.net/assets/img/icon.svg
collections:
  - name: "posts"
    label: "Posts"
    folder: "_src/posts"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Slug", name: "pageSlug", widget: "string", required: false }
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Description", name: "desc", widget: "string" }
      - {label: "Date", name: "date", widget: "datetime" }
      - {label: "Tags, separate with commas", name: "tags", widget: "list", required: false }
      - {label: "Author ID", name: "author", widget: "string" }
      - {label: "Image URL", name: "image", widget: "string" }
      - {label: "Image Source URL", name: "imageSource", widget: "string", required: false }
      - {label: "YouTube Video ID", name: "videoID", widget: "string", required: false }
      - {label: "Affiliate Links", name: "affiliateLinks", widget: "boolean", default: false, required: false}
      - {label: "Hide Ads", name: "hideAds", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown" }